Repository com-pas/compas-scl-validator, pull requests merged in 2022-03, with the labels that each got.

#31 Fix bug that old validation results are also returned
  app/src/test/data/ocl/Busbar.ocl
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/impl/OclFileLoader.java
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/impl/SclModelLoader.java
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/impl/SclRiseClipseValidator.java
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/util/OclUtil.java
  riseclipse/validator-riseclipse/src/test/data/ocl/Busbar.ocl
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/impl/OclFileLoaderTest.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/impl/SclModelLoaderTest.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/impl/SclRiseClipseValidatorTest.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/util/OclUtilTest.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/util/TestSupportUtil.java
  riseclipse/validator-riseclipse/src/test/resources/ocl-testfiles/example.ocl
  riseclipse/validator-riseclipse/src/test/resources/ocl-testfiles/invalid.ocl
Labels: bug

#33 Added logging to show list of OCL Files found.
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/collector/CompasOclFileCollector.java
Labels: enhancement

#37 Fixed the Release Action
  .github/workflows/release-project.yml
  app/src/main/resources/application.properties
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/collector/AbstractFileCollector.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/impl/SclModelLoaderTest.java
  riseclipse/validator-riseclipse/src/test/resources/simplelogger.properties
Labels: bug

#39 Updated README.md with information about OCL Files
  README.md
Labels: enhancement

#44 Update instruction for IntelliJ
  DEVELOPMENT.md
Labels: tooling

#40 Add XSD Validation
  app/src/main/java/org/lfenergy/compas/scl/validator/rest/CompasSclValidatorConfiguration.java
  app/src/test/java/org/lfenergy/compas/scl/validator/rest/CompasSclValidatorConfigurationTest.java
  pom.xml
  riseclipse/validator-riseclipse/src/main/java/org/lfenergy/compas/scl/validator/impl/SclRiseClipseValidator.java
  riseclipse/validator-riseclipse/src/test/java/org/lfenergy/compas/scl/validator/impl/SclRiseClipseValidatorTest.java
  service/src/main/java/org/lfenergy/compas/scl/validator/service/SclValidatorService.java
  service/src/test/java/org/lfenergy/compas/scl/validator/service/SclValidatorServiceTest.java
  validator/pom.xml
  validator/src/main/java/org/lfenergy/compas/scl/validator/exception/SclValidatorErrorCode.java
  validator/src/main/java/org/lfenergy/compas/scl/validator/xsd/SclInfo.java
  validator/src/main/java/org/lfenergy/compas/scl/validator/xsd/SclXsdValidator.java
  validator/src/main/java/org/lfenergy/compas/scl/validator/xsd/XSDValidator.java
  validator/src/main/java/org/lfenergy/compas/scl/validator/xsd/resourceresolver/ResourceInput.java
  validator/src/main/java/org/lfenergy/compas/scl/validator/xsd/resourceresolver/ResourceResolver.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/util/StaxUtilTest.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/xsd/SclInfoTest.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/xsd/SclXsdValidatorTest.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/xsd/XSDValidatorTest.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/xsd/resourceresolver/ResourceInputTest.java
  validator/src/test/java/org/lfenergy/compas/scl/validator/xsd/resourceresolver/ResourceResolverTest.java
  validator/src/test/resources/scl/example.scd
  validator/src/test/resources/scl/invalid.scd
  validator/src/test/resources/scl/validation/example-with-missing-version.scd
  validator/src/test/resources/scl/validation/example-with-wrong-version.scd
  validator/src/test/resources/scl/validation/example-with-xsd-validation-errors.scd
  validator/src/test/resources/scl/validation/example-without-xsd-validation-errors.scd
Labels: enhancement
